# Generated by Django 4.0.5 on 2022-06-15 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0002_articletags_tag_articletags_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='articles',
            field=models.ManyToManyField(related_name='tags', through='articles.ArticleTags', to='articles.article'),
        ),
    ]
