# Generated by Django 4.0.5 on 2022-06-15 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0004_scope_alter_tag_articles_delete_articletags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tag',
            name='url',
            field=models.CharField(default=12345, max_length=40),
        ),
    ]
